---

- name: config > Templates
  template:
    src:  "{{ item.template }}"
    dest: "{{ shorewall_configs_dir }}/{{ item.file }}"
  with_items: shorewall_configs
#  notify:
#    - shorewall restart
