---
- name: Set ip_forward
  ansible.builtin.lineinfile:
    dest: /etc/shorewall/shorewall.conf
    line: IP_FORWARDING={{ shorewall_ipforward }}
    regexp: ^IP_FORWARDING=
    state: present
  notify: Shorewall restart

- name: Config > Templates
  ansible.builtin.template:
    src: "{{ item.key }}.j2"
    dest: "{{ shorewall_configs_dir }}/{{ item.key }}"
  with_dict: "{{ shorewall_configs }}"
  notify: Shorewall restart

- name: Config interfaces
  ansible.builtin.template:
    src: interfaces.j2
    dest: "{{ shorewall_configs_dir }}/interfaces"
  notify: Shorewall restart

- name: Configure shorewall service autostart
  ansible.builtin.service:
    name: shorewall
    enabled: "{{ 'yes' if shorewall_startup == 1 else 'no' }}"
