---
- name: Install > Packages
  ansible.builtin.apt:
    state: present
    pkg: shorewall

- name: Enable startup at boot
  ansible.builtin.lineinfile:
    dest: /etc/default/shorewall
    line: startup={{ shorewall_startup }}
    regexp: ^startup=
    state: present

- name: Install shorewall6
  ansible.builtin.apt:
    name: shorewall6
  when: not shorewall6_configs
