---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    
- ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks:
    file: configs.yml

- ansible.builtin.include_tasks:
    file: configsipv6.yml
  when: shorewall6_enable
