---
- name: Shorewall restart
  ansible.builtin.service:
    name: shorewall
    state: "{{ 'restarted' if shorewall_startup == 1 else 'stopped' }}"

- name: Shorewall6 restart
  ansible.builtin.service:
    name: shorewall6
    state: restarted
